version: '3.8'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.16
    container_name: bind9
    volumes:
      - ./bind9/conf:/etc/bind
      - ./bind9/data:/var/lib/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
