dns-server/
├── docker-compose.yml
└── bind9/
    ├── conf/
    │   ├── named.conf
    │   ├── named.conf.local
    │   ├── named.conf.options
    │   └── zones/
    │       ├── db.example.com
    │       └── db.192.168.1
    └── data/
        └── (동적으로 생성되는 파일들, 예: 로그 파일)
